base:
  batch_seqlen: 512
  hidden_dim: 512
  seq_len: 500
  projection_dim: 2048
  n_heads: 8
  head_dim: 64
  n_enc_layers: 6
  n_dec_layers: 6
  dropout_rate: 0.1
  dropatt_rate: 0.0
  pre_lnorm: False

large:
  batch_seqlen: 1024
  hidden_dim: 1024
  seq_len: 500
  projection_dim: 4096
  n_heads: 16
  head_dim: 64
  n_enc_layers: 10
  n_dec_layers: 2
  n_layers: 18
  dropout_rate: 0.1
  dropatt_rate: 0.0
  pre_lnorm: False

