n_epoch: 5
relative_pos: False
gathered: True
device: 'cuda'
batch_size: 16
gpu0_size: 8
update_step: 8
mixed_precision: True
decay_step: 20000
vocab_size: 30000
warmup_step: 4000
clip_norm: 0.25
learning_rate: 0.0005
weight_decay: 0.0001
